
GG = gcc -Wall -Werror -Wextra

InkFile = point.c
InheritFile = namedPoint.c main.c
PolymorphFile = copy.c

inkapsulacia: $(InkFile)
	$(GG) $(InkFile)


inheritance: $(InheritFile)
	$(GG) $(InheritFile)

polymorphism: $(PolymorphFile)
	$(GG) $(PolymorphFile)

